<?php

namespace AppBundle\Repository;

/**
 * BinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BinRepository extends \Doctrine\ORM\EntityRepository
{
}
