<?php

namespace AppBundle\Repository;

/**
 * ScreenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenRepository extends \Doctrine\ORM\EntityRepository
{
}
